clear;
ROOTPATH = "K:\ANALYSIS_202307_RatECOG_StartEndEffect\";
Fatherfileinfo = dir(ROOTPATH);
Fatherfileinfo(~[Fatherfileinfo.isdir]) = [];    
Fatherfileinfo(cell2mat(cellfun(@(x) strcmp(x, '.') || strcmp(x, '..'), {Fatherfileinfo.name}, "UniformOutput", false))) = [];
%% get params .mat & load variables
n = 1;
for FatherdirIdx = 1 : numel(Fatherfileinfo)
    Sondirinfo = dir(fullfile(ROOTPATH, Fatherfileinfo(FatherdirIdx).name));
    Sondirinfo(cell2mat(cellfun(@(x) strcmp(x, '.') || strcmp(x, '..'), {Sondirinfo.name},"UniformOutput", false))) = [];
    for sondirIdx = 1 : numel(Sondirinfo)
        clearvars -except n ROOTPATH FatherdirIdx Fatherfileinfo sondirIdx Sondirinfo ...
            ProtocolType_temp TrialType_temp f0_temp Diffratio_temp GroupTypes_temp Duration_temp ...
            StdNum_temp ChangeDuration_temp ChangePosition_temp trialonset_Window_temp ICAWindow_temp plotWindow_temp
        load(fullfile(ROOTPATH, Fatherfileinfo(FatherdirIdx).name, Sondirinfo(sondirIdx).name, "SEeffectparams.mat"));
        
        ProtocolType_temp{n, 1} = Fatherfileinfo(FatherdirIdx).name;
        parseStruct(SEeffectparams);
        TrialType_temp{n, 1} = join(TrialTypes, ",");
        f0_temp{n, 1} = string(f0);
        if ~exist("Diffratio", "var")
            Diffratio_temp{n, 1} = strrep(string(regexpi(ProtocolType_temp{n, 1}, 'dev(.*?)_change', 'tokens')), '_', ',');
            groupNum = numel(regexpi(Diffratio_temp{n, 1}, ',', 'split'));
        else
            Diffratio_temp{n, 1} = join(string(Diffratio), ',');
        end
        if ~exist("GroupTypes", "var")
            if groupNum == 3
                GroupTypes_temp{n, 1} = "1,2,3,4;1,5,6,7;1,8,9,10";
            elseif groupNum == 2
                GroupTypes_temp{n, 1} = "1,2,3,4;1,5,6,7";
            end
        else
            GroupTypes_temp{n, 1} = join(string(cellfun(@(x) join(x, ','), cellfun(@string, GroupTypes, 'UniformOutput', false), ...
                'UniformOutput', false)), ';');
        end
        if ~exist("Duration", "var")
            Duration_temp{n, 1} = string(regexpi(ProtocolType_temp{n, 1}, 'Dur(.*?)_dev', 'tokens'));
        else
            Duration_temp{n, 1} = string(Duration);
        end
        if contains(ProtocolType_temp{n, 1}, "Single")
            StdNum_temp{n, 1} = nan;
        else
            StdNum_temp{n, 1} = string(StdNum); 
        end
        if ~exist("ChangeDuration", "var") && exist("ChangePercent", "var")
            ChangeDuration_temp{n, 1} = string(Duration * ChangePercent);
        else
            ChangeDuration_temp{n, 1} = string(ChangeDuration); 
        end
        ChangePosition_temp{n, 1} = join(string(ChangePosition), ',');
        trialonset_Window_temp{n, 1} = join(string(trialonset_Window), ',');
        ICAWindow_temp{n, 1} = join(string(ICAWindow), ',');
        plotWindow_temp{n, 1} = join(string(plotWindow), ',');

        n = n + 1;
    end
end
%%
SoundPath = cell(n - 1 ,1);
VarNames = {["ProtocolType", ...
        "TrialType", ...
        "f0", ...
        "Diffratio", ...
        "GroupTypes", ...
        "Duration", ...
        "StdNum", ...
        "ChangeDuration", ...
        "ChangePosition", ...
        "SoundPath", ...
        "trialonset_Window", ...
        "ICAWindow", ...
        "plotWindow"]};
DataAll = table(ProtocolType_temp, ...
    TrialType_temp, ...
    f0_temp, ...
    Diffratio_temp, ...
    GroupTypes_temp, ...
    Duration_temp, ...
    StdNum_temp, ...
    ChangeDuration_temp, ...
    ChangePosition_temp, ...
    SoundPath, ...
    trialonset_Window_temp, ...
    ICAWindow_temp, ...
    plotWindow_temp, ...
    'VariableNames', VarNames{1});
writetable(DataAll, "K:\Program\RatECOG_StartEndEffect\SE.xlsx");

